### PR TITLE
This is how I look today with a missing tooth

### PR DESCRIPTION
**Pull request by Shazwazza**
Yep! I'm straight up hillbilly these days! Gonna be another few months before I can get this thing fixed up so until then this is me :)

### CODE REVIEW

**Comment by marcemarc** [comment]
that's an ice hockey grin...

**Comment by Shazwazza** [comment]
Yep, will earn me some hockey cred when the season starts up again. Kinda hoping it's not fixed by then 😂

**Comment by LottePitcher** [comment]
Ouch! So I assume you realise that you're going to have to bring your hockey gear to CG21 to do the big re-enactment!  I was going to have a go at merging your PR but we need a bigger garden and that's a bit beyond my photoshop skills.  But soon, my toothless hockey playing friend, soon!

**Comment by LottePitcher** [comment]
Hmmm.... "toothless" suggests you have no teeth. You clearly have (normal_teeth_count-1) teeth. Sorry.

**Comment by Shazwazza** [comment]
Here's the full status 🤓 

```cs
var orig = Enumerable.Range(0, normal_teeth_count).Select(i => (ITooth)new DefaultTooth()).ToList();
orig.RemoveRange(0, 8);
orig.AddRange(
	Enumerable.Range(0, 6).Select(i => new FilledTooth())
		.Concat(new ITooth[] { new Crown(), new Crown(atachedBy:AttachMethod.Post) }));
var curr = orig.RemoveWhere(x => x is Crown c && c.AttachedBy == AttachMethod.Post);
var future = curr.Concat(new ITooth[] { _implantWidth < healedWidth ? new Implant() : new Bridge() }); 
```

**Comment by lars-erik** [comment]
I think you're mixing `DefaultTooth()` in line 1 with `PrimaryTooth()`, tho.  
That code might only work on Toddler V1.  
https://en.wikipedia.org/wiki/Deciduous_teeth

**Comment by marcemarc** [comment]
> Here's the full status 🤓
> 
> ```cs
> var orig = Enumerable.Range(0, normal_teeth_count).Select(i => (ITooth)new DefaultTooth()).ToList();
> orig.RemoveRange(0, 8);
> orig.AddRange(
> 	Enumerable.Range(0, 6).Select(i => new FilledTooth())
> 		.Concat(new ITooth[] { new Crown(), new Crown(atachedBy:AttachMethod.Post) }));
> var curr = orig.RemoveWhere(x => x is Crown c && c.AttachedBy == AttachMethod.Post);
> var future = curr.Concat(new ITooth[] { _implantWidth < healedWidth ? new Implant() : new Bridge() }); 
> ```

I like your appropriate use of 'braces' in the meantime...

**Pull request merged**
