### PR TITLE
Adds Tim and the queens to the another dimension project

### PR DESCRIPTION
**Pull request by TimGeyssens**

### CODE REVIEW

**Comment by lars-erik** [comment]
Sweet! :D
First VR PR. 🎉🤘
Hopefully get more time tonight.

**Comment by lars-erik** [comment]
Don't wanna be a d**k about placement, but a bit concerned -6,18 makes it a bit too crowded.
If peeps' panels are too close and align perfectly, threejs cancels out rendering so they go invisible.

Trying to maintain a map with decent spread in this Excel-file:  
https://github.com/lars-erik/codegarden-2020-group-image/blob/another-dimension/Garden%20App/Placement%20Matrix.xlsx

**Comment by TimGeyssens** [comment]
ok sure, will update

**Comment by TimGeyssens** [comment]
updated to 1, 11

**Comment by lars-erik** [comment]
Awesome! Hope you're still visible.  
A bit unsure how to balance visibility from start vs. cool discovery while walking around. :)

**Comment by TimGeyssens** [comment]
I guess can still be finetuned onces all the pictures have been submitted :)

**Pull request merged**
