### PR TITLE
Misc images

### PR DESCRIPTION
**Pull request by BatJan**
A few different images that might be of use - Including some of the rover :-)

### CODE REVIEW

**Comment by lars-erik** [comment]
We're so gonna need to expand the garden. 🤣
Cheers a lot for this!

**Comment by BatJan** [comment]
Yeah soon it will be very cramped 😆 No worries I might do some more PR's later 😃 Keep up the good work and have fun!

**Comment by LottePitcher** [comment]
Some wonderful space fillers there Jan, wonderful stuff!

**Comment by LottePitcher** [comment]
Ooops, just realised that means I referred to Slave & Eagle as a "space filler" 🤭 😆

**Pull request merged**
